from pydantic import BaseModel, Field


class AdvisoryResponse(BaseModel):
    """
    Structured response generated by the LLM for a citizen
    air-pollution health advisory.
    """

    risk_level: str = Field(
        description="Overall personalized risk level. "
                    "Use only the risk level supplied by the deterministic assessment."
    )

    summary: str = Field(
        description="A short, simple personalized summary for the citizen."
    )

    todays_recommendations: list[str] = Field(
        description="Practical recommendations for today. "
                    "Each recommendation must be a separate string."
    )

    activity_timing: str = Field(
        description="Guidance about when and how the citizen should perform "
                    "the planned activity."
    )

    outdoor_exposure: str = Field(
        description="Guidance about outdoor exposure based on the supplied AQI "
                    "and evidence."
    )

    protective_measures: list[str] = Field(
        description="Evidence-supported protective measures. "
                    "Each measure must be a separate string."
    )

    warning_signs: list[str] = Field(
        description="Evidence-supported warning symptoms. "
                    "Each symptom must be a separate string."
    )

    evidence_sources: list[str] = Field(
        description="Knowledge-base source filenames used for the advisory. "
                    "Each filename must be a separate string."
    )

    disclaimer: str = Field(
        description="Clear statement that this is general health guidance "
                    "and not medical diagnosis or treatment."
    )