import { useState } from 'react'
import ProfileForm from '../components/ProfileForm'
import AdvisoryResult from '../components/AdvisoryResult'
import ErrorState from '../components/ErrorState'
import SectionHeader from '../components/SectionHeader'
import { useAdvisory } from '../hooks/useAdvisory'
import { formatCoordinates } from '../utils/constants'

const initialValues = { age_group: '', health_conditions: [], activity_level: '' }
export default function Health() { const [values, setValues] = useState(initialValues); const [detectedLocation, setDetectedLocation] = useState(null); const [locationMessage, setLocationMessage] = useState('Your location is requested only when you generate an advisory.'); const advisory = useAdvisory(); const submit = (event) => { event.preventDefault(); if (!values.age_group || !values.activity_level || !values.health_conditions.length) { setLocationMessage('Choose an age group, activity level, and at least one health-condition state.'); return } if (!navigator.geolocation) { setLocationMessage('This browser does not support location access.'); return } setLocationMessage('Requesting your current location...'); navigator.geolocation.getCurrentPosition(({ coords }) => { const location = { latitude: coords.latitude, longitude: coords.longitude }; setDetectedLocation(formatCoordinates(location.latitude, location.longitude)); setLocationMessage('Location received.'); console.log('Personalized advisory location:', location); advisory.submit({ ...values, ...location }) }, () => setLocationMessage('Location permission is required to generate a personalized advisory.')) }; return <><div className="page-intro health-intro"><div><span className="eyebrow">Personalized health advisory</span><h1>Plan your day with context.</h1><p>Get customized recommendations based on your health profile and planned activities.</p></div></div><div className="health-layout"><div><SectionHeader eyebrow="Your profile" title="Tell us about yourself" /><ProfileForm values={values} setValues={setValues} onSubmit={submit} loading={advisory.loading} locationMessage={locationMessage} detectedLocation={detectedLocation} /></div><div className="result-column">{advisory.error && <ErrorState message={advisory.error} />}{advisory.loading && <div className="card loading-state">Generating your personalized advisory...</div>}{advisory.data ? <AdvisoryResult result={advisory.data} /> : !advisory.loading && <div className="card empty-result"><span className="empty-icon">✦</span><h3>Your advisory will appear here</h3><p>Complete your profile and allow location access to receive guidance from the backend.</p></div>}</div></div></> }
